export const personajesCrepusculo = [
  {
    id: 1,
    nombre: "Edward Cullen",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion:
      "Un vampiro centenario que brilla bajo el sol y se enamora de una humana.",
    imagen: "img/edward.jpg",
  },
  {
    id: 2,
    nombre: "Bella Swan",
    genero: "Mujer",
    tipo: "Humana/Vampiro",
    peliculas: 5,
    estadoFinal: "Viva (convertida en vampiro)",
    pareja: true,
    descripcion:
      "Una humana que se convierte en vampiro tras casarse con su amor inmortal.",
    imagen: "img/bella.webp",
  },
  {
    id: 3,
    nombre: "Alice Cullen",
    genero: "Mujer",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Viva",
    pareja: true,
    descripcion: "Vampira con un estilo único y la habilidad de ver el futuro.",
    imagen: "img/alice.webp",
  },
  {
    id: 4,
    nombre: "Jasper Hale",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion: "Un vampiro que controla emociones, con un pasado militar.",
    imagen: "img/jasper.webp",
  },
  {
    id: 5,
    nombre: "Carlisle Cullen",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion:
      "El patriarca de la familia Cullen, conocido por su bondad y sabiduría.",
    imagen: "img/carlisle.webp",
  },
  {
    id: 6,
    nombre: "Esme Cullen",
    genero: "Mujer",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Viva",
    pareja: true,
    descripcion: "La matriarca de los Cullen, siempre cuidando de su familia.",
    imagen: "img/esme.webp",
  },
  {
    id: 7,
    nombre: "Rosalie Hale",
    genero: "Mujer",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Viva",
    pareja: true,
    descripcion:
      "Una vampira con una belleza impresionante y un pasado trágico.",
    imagen: "img/rosalie.webp",
  },
  {
    id: 8,
    nombre: "Emmett Cullen",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 5,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion:
      "El vampiro más fuerte de la familia Cullen, conocido por su humor.",
    imagen: "img/emmett.webp",
  },
  {
    id: 9,
    nombre: "Jacob Black",
    genero: "Hombre",
    tipo: "Lobo",
    peliculas: 5,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion:
      "Un hombre lobo con un amor no correspondido y un vínculo especial con Renesmee.",
    imagen: "img/jacob.webp",
  },
  {
    id: 10,
    nombre: "Renesmee Cullen",
    genero: "Mujer",
    tipo: "Híbrido Humano-Vampiro",
    peliculas: 2,
    estadoFinal: "Viva",
    pareja: true,
    descripcion:
      "Hija de Edward y Bella, una híbrida única con un don especial.",
    imagen: "img/renesmee.webp",
  },
  {
    id: 11,
    nombre: "Victoria",
    genero: "Mujer",
    tipo: "Vampiro",
    peliculas: 3,
    estadoFinal: "Muerta",
    pareja: true,
    descripcion: "Una vampira vengativa que busca destruir a Bella.",
    imagen: "img/victoria.webp",
  },
  {
    id: 12,
    nombre: "James",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 1,
    estadoFinal: "Muerto",
    pareja: true,
    descripcion: "Un vampiro rastreador que pone en peligro a Bella.",
    imagen: "img/james.webp",
  },
  {
    id: 13,
    nombre: "Laurent",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 2,
    estadoFinal: "Muerto",
    pareja: false,
    descripcion: "Un vampiro neutral que se une brevemente a los Cullen.",
    imagen: "img/laurent.webp",
  },
  {
    id: 14,
    nombre: "Charlie Swan",
    genero: "Hombre",
    tipo: "Humano",
    peliculas: 5,
    estadoFinal: "Vivo",
    pareja: false,
    descripcion: "El padre humano de Bella, protector y desconfiado.",
    imagen: "img/charlie.webp",
  },
  {
    id: 15,
    nombre: "Sam Uley",
    genero: "Hombre",
    tipo: "Lobo",
    peliculas: 4,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion:
      "El líder de la manada de lobos, siempre velando por su comunidad.",
    imagen: "img/sam.webp",
  },
  {
    id: 16,
    nombre: "Leah Clearwater",
    genero: "Mujer",
    tipo: "Lobo",
    peliculas: 3,
    estadoFinal: "Viva",
    pareja: false,
    descripcion: "La única mujer lobo de la manada, fuerte y decidida.",
    imagen: "img/leah.webp",
  },
  {
    id: 17,
    nombre: "Seth Clearwater",
    genero: "Hombre",
    tipo: "Lobo",
    peliculas: 3,
    estadoFinal: "Vivo",
    pareja: false,
    descripcion: "Un joven lobo leal y lleno de energía.",
    imagen: "img/seth.webp",
  },
  {
    id: 18,
    nombre: "Emily Young",
    genero: "Mujer",
    tipo: "Humana",
    peliculas: 2,
    estadoFinal: "Viva",
    pareja: true,
    descripcion: "La pareja de Sam, marcada por un accidente en su rostro.",
    imagen: "img/emily.webp",
  },
  {
    id: 19,
    nombre: "Aro",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 4,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion: "El líder de los Volturi, ambicioso y calculador.",
    imagen: "img/aro.webp",
  },
  {
    id: 20,
    nombre: "Caius",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 4,
    estadoFinal: "Vivo",
    pareja: true,
    descripcion: "Un miembro de los Volturi, temido por su crueldad.",
    imagen: "img/caius.webp",
  },
  {
    id: 21,
    nombre: "Marcus",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 4,
    estadoFinal: "Vivo",
    pareja: false,
    descripcion: "Un Volturi con el don de percibir relaciones.",
    imagen: "img/marcus.jpg",
  },
  {
    id: 22,
    nombre: "Jane",
    genero: "Mujer",
    tipo: "Vampiro",
    peliculas: 4,
    estadoFinal: "Viva",
    pareja: false,
    descripcion: "Una vampira Volturi con el poder de causar dolor mental.",
    imagen: "img/jane.webp",
  },
  {
    id: 23,
    nombre: "Alec",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 4,
    estadoFinal: "Vivo",
    pareja: false,
    descripcion: "Un Volturi con la habilidad de bloquear sentidos.",
    imagen: "img/alec.jpg",
  },
  {
    id: 24,
    nombre: "Felix",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 3,
    estadoFinal: "Vivo",
    pareja: false,
    descripcion: "El músculo de los Volturi, siempre listo para luchar.",
    imagen: "img/felix.webp",
  },
  {
    id: 25,
    nombre: "Demetri",
    genero: "Hombre",
    tipo: "Vampiro",
    peliculas: 3,
    estadoFinal: "Vivo",
    pareja: false,
    descripcion:
      "Un rastreador Volturi, con un talento excepcional para encontrar personas.",
    imagen: "img/demetri.webp",
  },
];
