const personajesCrepusculo = [
    {
      nombre: "Edward Cullen",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Bella Swan",
      genero: "Mujer",
      tipo: "Humana/Vampiro",
      peliculas: 5,
      estadoFinal: "Viva (convertida en vampiro)",
      pareja: true,
    },
    {
      nombre: "Alice Cullen",
      genero: "Mujer",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Viva",
      pareja: true,
    },
    {
      nombre: "Jasper Hale",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Carlisle Cullen",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Esme Cullen",
      genero: "Mujer",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Viva",
      pareja: true,
    },
    {
      nombre: "Rosalie Hale",
      genero: "Mujer",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Viva",
      pareja: true,
    },
    {
      nombre: "Emmett Cullen",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 5,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Jacob Black",
      genero: "Hombre",
      tipo: "Lobo",
      peliculas: 5,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Renesmee Cullen",
      genero: "Mujer",
      tipo: "Híbrido Humano-Vampiro",
      peliculas: 2,
      estadoFinal: "Viva",
      pareja: true,
    },
    {
      nombre: "Victoria",
      genero: "Mujer",
      tipo: "Vampiro",
      peliculas: 3,
      estadoFinal: "Muerta",
      pareja: true,
    },
    {
      nombre: "James",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 1,
      estadoFinal: "Muerto",
      pareja: true,
    },
    {
      nombre: "Laurent",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 2,
      estadoFinal: "Muerto",
      pareja: false,
    },
    {
      nombre: "Charlie Swan",
      genero: "Hombre",
      tipo: "Humano",
      peliculas: 5,
      estadoFinal: "Vivo",
      pareja: false,
    },
    {
      nombre: "Sam Uley",
      genero: "Hombre",
      tipo: "Lobo",
      peliculas: 4,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Leah Clearwater",
      genero: "Mujer",
      tipo: "Lobo",
      peliculas: 3,
      estadoFinal: "Viva",
      pareja: false,
    },
    {
      nombre: "Seth Clearwater",
      genero: "Hombre",
      tipo: "Lobo",
      peliculas: 3,
      estadoFinal: "Vivo",
      pareja: false,
    },
    {
      nombre: "Emily Young",
      genero: "Mujer",
      tipo: "Humana",
      peliculas: 2,
      estadoFinal: "Viva",
      pareja: true,
    },
    {
      nombre: "Aro",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 4,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Caius",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 4,
      estadoFinal: "Vivo",
      pareja: true,
    },
    {
      nombre: "Marcus",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 4,
      estadoFinal: "Vivo",
      pareja: false,
    },
    {
      nombre: "Jane",
      genero: "Mujer",
      tipo: "Vampiro",
      peliculas: 4,
      estadoFinal: "Viva",
      pareja: false,
    },
    {
      nombre: "Alec",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 4,
      estadoFinal: "Vivo",
      pareja: false,
    },
    {
      nombre: "Felix",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 3,
      estadoFinal: "Vivo",
      pareja: false,
    },
    {
      nombre: "Demetri",
      genero: "Hombre",
      tipo: "Vampiro",
      peliculas: 3,
      estadoFinal: "Vivo",
      pareja: false,
    },
  ];
    